# Generated by Django 5.1.2 on 2026-03-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0002_add_bank_account"),
        ("sea_saw_procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier bank account for payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="sea_saw_crm.bankaccount",
                verbose_name="Bank Account",
            ),
        ),
    ]
