# Generated by Django 5.1.2 on 2026-04-11 13:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sea_saw_procurement",
            "0003_purchaseorder_buyer_shipper_payment_terms_additional_info",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="glazing",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="Glazing (%)",
            ),
        ),
    ]
