# Generated by Django 5.1.2 on 2026-03-14 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_download", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadtask",
            name="download_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="downloadtask",
            name="task_id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=36, unique=True
            ),
        ),
    ]
