# Generated by Django 5.1.2 on 2026-02-04 05:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sea_saw_crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "etd",
                    models.DateField(
                        blank=True,
                        help_text="Estimated time of departure.",
                        null=True,
                        verbose_name="ETD",
                    ),
                ),
                (
                    "loading_port",
                    models.CharField(
                        blank=True,
                        default="Any port of CHINA",
                        max_length=100,
                        null=True,
                        verbose_name="Loading Port",
                    ),
                ),
                (
                    "destination_port",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Destination Port",
                    ),
                ),
                (
                    "shipment_term",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sea", "Sea"),
                            ("air", "Air"),
                            ("rail", "Rail"),
                            ("road", "Road"),
                            ("multimodal", "Multimodal"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Shipment Term",
                    ),
                ),
                (
                    "inco_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXW", "EXW - Ex Works"),
                            ("FCA", "FCA - Free Carrier"),
                            ("CPT", "CPT - Carriage Paid To"),
                            ("CIP", "CIP - Carriage and Insurance Paid To"),
                            ("DAP", "DAP - Delivered at Place"),
                            ("DPU", "DPU - Delivered at Place Unloaded"),
                            ("DDP", "DDP - Delivered Duty Paid"),
                            ("FAS", "FAS - Free Alongside Ship"),
                            ("FOB", "FOB - Free on Board"),
                            ("CFR", "CFR - Cost and Freight"),
                            ("CIF", "CIF - Cost, Insurance and Freight"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="Inco Terms",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CNY", "CNY"),
                            ("HKD", "HKD"),
                            ("JPY", "JPY"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Deposit",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Balance",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "order_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for this order.",
                        max_length=100,
                        unique=True,
                        verbose_name="Order Code",
                    ),
                ),
                (
                    "order_date",
                    models.DateField(blank=True, null=True, verbose_name="Order Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("issue_reported", "Issue Reported"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="Order Status",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer account for this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="sea_saw_crm.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contact person for this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="sea_saw_crm.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Product Name"),
                ),
                (
                    "specification",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Specification",
                    ),
                ),
                (
                    "outter_packaging",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Outter Packaging",
                    ),
                ),
                (
                    "inner_packaging",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Inner Packaging",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Size"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("kgs", "KGS"), ("lbs", "LBS")],
                        default="kgs",
                        max_length=20,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "glazing",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Glazing (%)",
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Gross Weight",
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Net Weight",
                    ),
                ),
                (
                    "order_qty",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Order Quantity"
                    ),
                ),
                (
                    "total_gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Gross Weight",
                    ),
                ),
                (
                    "total_net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Net Weight",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        verbose_name="Total Price",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="sea_saw_sales.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_code"], name="sea_saw_sal_order_c_34358d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="sea_saw_sal_status_047a6a_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["account"], name="sea_saw_sal_account_77370b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product_name"], name="sea_saw_sal_product_ebf39c_idx"
            ),
        ),
    ]
