# Generated by Django 5.1.2 on 2026-03-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_sales", "0002_order_status_simplify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=32,
                verbose_name="Order Status",
            ),
        ),
    ]
