# Generated by Django 5.1.2 on 2026-04-11 13:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sea_saw_sales",
            "0005_order_buyer_seller_shipper_additional_info_payment_terms",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE indexname = 'sea_saw_sal_buyer_idx'
                    ) THEN
                        ALTER INDEX "sea_saw_sal_buyer_idx"
                            RENAME TO "sea_saw_sal_buyer_i_653395_idx";
                    END IF;
                END$$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE indexname = 'sea_saw_sal_buyer_i_653395_idx'
                    ) THEN
                        ALTER INDEX "sea_saw_sal_buyer_i_653395_idx"
                            RENAME TO "sea_saw_sal_buyer_idx";
                    END IF;
                END$$;
            """,
        ),
        migrations.AlterField(
            model_name="order",
            name="additional_info",
            field=models.TextField(
                blank=True,
                help_text="Additional information for document templates.",
                null=True,
                verbose_name="Additional Info",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_terms",
            field=models.TextField(
                blank=True,
                help_text="Free-text payment terms.",
                null=True,
                verbose_name="Term/Method of Payment",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="glazing",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="Glazing (%)",
            ),
        ),
    ]
