# Generated by Django 5.1.2 on 2026-02-04 05:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sea_saw_pipeline", "0001_initial"),
        ("sea_saw_production", "0001_initial"),
        ("sea_saw_sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "outbound_code",
                    models.CharField(
                        help_text="Unique outbound / shipment code.",
                        max_length=100,
                        unique=True,
                        verbose_name="Outbound Code",
                    ),
                ),
                (
                    "outbound_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Outbound Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("issue_reported", "Issue Reported"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "container_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Container No.",
                    ),
                ),
                (
                    "seal_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Seal No."
                    ),
                ),
                (
                    "destination_port",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Destination Port",
                    ),
                ),
                (
                    "logistics_provider",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Logistics Provider",
                    ),
                ),
                (
                    "loader",
                    models.CharField(
                        blank=True,
                        help_text="Person who loads the goods into the container.",
                        max_length=255,
                        null=True,
                        verbose_name="Loader",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="Remark"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        help_text="The business process pipeline this outbound order belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_orders",
                        to="sea_saw_pipeline.pipeline",
                        verbose_name="Pipeline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbound Order",
                "verbose_name_plural": "Outbound Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Product Name"),
                ),
                (
                    "specification",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Specification",
                    ),
                ),
                (
                    "outter_packaging",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Outter Packaging",
                    ),
                ),
                (
                    "inner_packaging",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Inner Packaging",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Size"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("kgs", "KGS"), ("lbs", "LBS")],
                        default="kgs",
                        max_length=20,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "glazing",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Glazing (%)",
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Gross Weight",
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Net Weight",
                    ),
                ),
                (
                    "outbound_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Outbound quantity (cartons / pieces).",
                        max_digits=10,
                        verbose_name="Outbound Quantity",
                    ),
                ),
                (
                    "outbound_net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Outbound Net Weight",
                    ),
                ),
                (
                    "outbound_gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Outbound Gross Weight",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The sales order item associated with this outbound item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_items",
                        to="sea_saw_sales.orderitem",
                        verbose_name="Order Item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "production_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The production item associated with this outbound item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_items",
                        to="sea_saw_production.productionitem",
                        verbose_name="Production Item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "outbound_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_items",
                        to="sea_saw_warehouse.outboundorder",
                        verbose_name="Outbound Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbound Item",
                "verbose_name_plural": "Outbound Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="outboundorder",
            index=models.Index(
                fields=["outbound_code"], name="sea_saw_war_outboun_9cf256_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundorder",
            index=models.Index(fields=["status"], name="sea_saw_war_status_2c3da6_idx"),
        ),
        migrations.AddIndex(
            model_name="outbounditem",
            index=models.Index(
                fields=["outbound_qty"], name="sea_saw_war_outboun_9733c3_idx"
            ),
        ),
    ]
