# Generated by Django 5.1.2 on 2026-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundorder",
            name="eta",
            field=models.DateField(
                blank=True,
                help_text="Estimated time of arrival.",
                null=True,
                verbose_name="ETA",
            ),
        ),
    ]
