
# Generated by Django 5.1.2 on 2026-02-04 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sea_saw_crm", "0001_initial"),
        ("sea_saw_sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "pipeline_code",
                    models.CharField(
                        help_text="Unique identifier for this business process pipeline",
                        max_length=100,
                        unique=True,
                        verbose_name="Pipeline Code",
                    ),
                ),
                (
                    "pipeline_type",
                    models.CharField(
                        choices=[
                            ("production_flow", "Production Flow"),
                            ("purchase_flow", "Purchase Flow"),
                            ("hybrid_flow", "Hybrid Flow"),
                        ],
                        default="production_flow",
                        help_text="Type of business process flow",
                        max_length=50,
                        verbose_name="Pipeline Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("order_confirmed", "Order Confirmed"),
                            ("in_purchase", "In Purchase"),
                            ("purchase_completed", "Purchase Completed"),
                            ("in_production", "In Production"),
                            ("production_completed", "Production Completed"),
                            (
                                "in_purchase_and_production",
                                "In Purchase and Production",
                            ),
                            (
                                "purchase_and_production_completed",
                                "Purchase and Production Completed",
                            ),
                            ("in_outbound", "In Outbound"),
                            ("outbound_completed", "Outbound Completed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("issue_reported", "Issue Reported"),
                        ],
                        default="draft",
                        help_text="Current status of the business process",
                        max_length=50,
                        verbose_name="Pipeline Status",
                    ),
                ),
                (
                    "active_entity",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("order", "Order"),
                            ("production", "Production"),
                            ("purchase", "Purchase"),
                            ("production_and_purchase", "Production and Purchase"),
                            ("outbound", "Outbound"),
                        ],
                        default="none",
                        help_text="Currently active sub-entity type in this pipeline",
                        max_length=25,
                        verbose_name="Active Entity",
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the order was created",
                        null=True,
                        verbose_name="Order Date",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the order was confirmed",
                        null=True,
                        verbose_name="Confirmed At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the entire pipeline was completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the pipeline was cancelled",
                        null=True,
                        verbose_name="Cancelled At",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes for this pipeline",
                        null=True,
                        verbose_name="Remark",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer account for this pipeline",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipelines",
                        to="sea_saw_crm.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contact person for this pipeline",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipelines",
                        to="sea_saw_crm.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="The main sales order for this pipeline",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline",
                        to="sea_saw_sales.order",
                        verbose_name="Sales Order",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline",
                "verbose_name_plural": "Pipelines",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["pipeline_code"], name="sea_saw_pip_pipelin_408b59_idx"
                    ),
                    models.Index(
                        fields=["status"], name="sea_saw_pip_status_3ba35b_idx"
                    ),
                    models.Index(
                        fields=["pipeline_type"], name="sea_saw_pip_pipelin_898edb_idx"
                    ),
                    models.Index(
                        fields=["order_date"], name="sea_saw_pip_order_d_72c0d9_idx"
                    ),
                    models.Index(
                        fields=["account"], name="sea_saw_pip_account_cf6e03_idx"
                    ),
                ],
            },
        ),
    ]
