# Generated by Django 5.1.2 on 2025-12-11 07:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="The name of the company.",
                        max_length=255,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email of the company.",
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="The mobile phone number of the company.",
                        max_length=255,
                        null=True,
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="The landline phone number of the company.",
                        max_length=255,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="The address of the company.",
                        max_length=255,
                        null=True,
                        verbose_name="Address",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of the contact.",
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="The position or title of the contact.",
                        max_length=255,
                        null=True,
                        verbose_name="Job Title",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the contact.",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="Mobile phone number of the contact.",
                        max_length=50,
                        null=True,
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Landline phone number of the contact.",
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="The company associated with this contact.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="sea_saw_crm.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["name", "email"],
                "unique_together": {("email", "deleted")},
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "contract_code",
                    models.CharField(
                        help_text="Unique identifier for the contract.",
                        max_length=100,
                        unique=True,
                        verbose_name="Contract Code",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                            ("delayed", "Delayed"),
                            ("issue_reported", "Issue Reported"),
                        ],
                        default="in_progress",
                        max_length=32,
                        verbose_name="Stage",
                    ),
                ),
                (
                    "contract_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract Date"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="sea_saw_crm.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "order_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for this order.",
                        max_length=100,
                        unique=True,
                        verbose_name="Order Code",
                    ),
                ),
                (
                    "order_date",
                    models.DateField(blank=True, null=True, verbose_name="Order Date"),
                ),
                (
                    "etd",
                    models.DateField(
                        blank=True,
                        help_text="Estimated time of departure.",
                        null=True,
                        verbose_name="ETD",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("order_confirmed", "Order Confirmed"),
                            ("in_production", "In Production"),
                            ("production_completed", "Production Completed"),
                            ("in_outbound", "In Outbound"),
                            ("outbound_completed", "Outbound Completed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("issue_reported", "Issue Reported"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="Order Status",
                    ),
                ),
                (
                    "loading_port",
                    models.CharField(
                        blank=True,
                        default="Any port of CHINA",
                        max_length=100,
                        null=True,
                        verbose_name="Loading Port",
                    ),
                ),
                (
                    "destination_port",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Destination Port",
                    ),
                ),
                (
                    "shipment_term",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Shipment Term",
                    ),
                ),
                (
                    "inco_terms",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Inco Terms"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Currency"
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Deposit",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Balance",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="sea_saw_crm.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Product Name"),
                ),
                (
                    "specification",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Specification",
                    ),
                ),
                (
                    "outter_packaging",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Outter Packaging",
                    ),
                ),
                (
                    "inner_packaging",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Inner Packaging",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Size"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("kgs", "KGS"), ("lbs", "LBS")],
                        default="kgs",
                        max_length=20,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "glazing",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Glazing (%)",
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Gross Weight",
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Net Weight",
                    ),
                ),
                (
                    "order_qty",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Order Quantity"
                    ),
                ),
                (
                    "total_gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Gross Weight",
                    ),
                ),
                (
                    "total_net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Net Weight",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        verbose_name="Total Price",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sea_saw_crm.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboundOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "outbound_code",
                    models.CharField(
                        help_text="Unique outbound / shipment code.",
                        max_length=100,
                        unique=True,
                        verbose_name="Outbound Code",
                    ),
                ),
                (
                    "outbound_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Outbound Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("packed", "Packed"),
                            ("shipped", "Shipped"),
                            ("custom_cleared", "Custom Cleared"),
                            ("arrived", "Arrived"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "container_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Container No.",
                    ),
                ),
                (
                    "seal_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Seal No."
                    ),
                ),
                (
                    "destination_port",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Destination Port",
                    ),
                ),
                (
                    "logistics_provider",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Logistics Provider",
                    ),
                ),
                (
                    "loader",
                    models.CharField(
                        blank=True,
                        help_text="Person who loads the goods into the container.",
                        max_length=255,
                        null=True,
                        verbose_name="Loader",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="Remark"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales order this outbound belongs to (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_orders",
                        to="sea_saw_crm.order",
                        verbose_name="Related Order",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbound Order",
                "verbose_name_plural": "Outbound Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "payment_code",
                    models.CharField(
                        help_text="Unique identifier for this payment record.",
                        max_length=100,
                        unique=True,
                        verbose_name="Payment Code",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Payment amount received.",
                        max_digits=20,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency of the payment, e.g., USD, EUR.",
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TT", "Telegraphic Transfer"),
                            ("LC", "Letter of Credit"),
                            ("PayPal", "PayPal"),
                            ("Cash", "Cash"),
                            ("Bank Transfer", "Bank Transfer"),
                        ],
                        help_text="Method of payment, e.g., TT, LC, PayPal.",
                        max_length=50,
                        null=True,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank transaction reference number.",
                        max_length=255,
                        null=True,
                        verbose_name="Bank Reference",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Upload bank slip or proof of payment.",
                        null=True,
                        upload_to="payment_attachments/",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes regarding this payment.",
                        null=True,
                        verbose_name="Remark",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order this payment is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sea_saw_crm.order",
                        verbose_name="Related Order",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Record",
                "verbose_name_plural": "Payment Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "planned_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Planned Quantity",
                    ),
                ),
                (
                    "produced_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total actual produced quantity.",
                        max_digits=10,
                        verbose_name="Produced Quantity",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The sales order item linked to this production item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_items",
                        to="sea_saw_crm.orderitem",
                        verbose_name="Related Order Item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Item",
                "verbose_name_plural": "Production Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "outbound_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Outbound quantity (cartons / pieces).",
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "outbound_net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Outbound Net Weight",
                    ),
                ),
                (
                    "outbound_gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Outbound Gross Weight",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The sales order item associated with this outbound item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_items",
                        to="sea_saw_crm.orderitem",
                        verbose_name="Order Item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "outbound_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sea_saw_crm.outboundorder",
                        verbose_name="Outbound Order",
                    ),
                ),
                (
                    "production_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The production item associated with this outbound item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_items",
                        to="sea_saw_crm.productionitem",
                        verbose_name="Production Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbound Item",
                "verbose_name_plural": "Outbound Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "production_code",
                    models.CharField(
                        help_text="Unique code for the production order.",
                        max_length=100,
                        unique=True,
                        verbose_name="Production Code",
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Planned Date"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("paused", "Paused"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                            ("issue_reported", "Issue Reported"),
                        ],
                        default="draft",
                        help_text="Production status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes for this production order.",
                        null=True,
                        verbose_name="Remark",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes for this production order.",
                        null=True,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "production_files",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="production_files/",
                        verbose_name="Production Files",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales order that triggered this production (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders",
                        to="sea_saw_crm.order",
                        verbose_name="Related Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Order",
                "verbose_name_plural": "Production Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="productionitem",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="sea_saw_crm.productionorder",
                verbose_name="Production Order",
            ),
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who created this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="The user who last updated this object.",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Unique name of the field within the same content type.",
                        max_length=50,
                        verbose_name="Field Name",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("picklist", "Picklist"),
                            ("text", "Text"),
                            ("numerical", "Numerical"),
                            ("lookup", "Lookup"),
                            ("date", "Date"),
                            ("currency", "Currency"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("url", "URL"),
                        ],
                        default="text",
                        help_text="Type of this field, e.g., text, picklist, date.",
                        max_length=50,
                        verbose_name="Field Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the field is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this field is required.",
                        verbose_name="Is Mandatory",
                    ),
                ),
                (
                    "extra_info",
                    models.JSONField(
                        blank=True,
                        help_text="Optional metadata, e.g., picklist choices.",
                        null=True,
                        verbose_name="Extra Information",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The model that this field belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "field_name"),
                        name="unique_field_per_content_type",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_code"], name="sea_saw_crm_order_c_383188_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="sea_saw_crm_status_bce136_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product_name"], name="sea_saw_crm_product_4b8829_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundorder",
            index=models.Index(
                fields=["outbound_code"], name="sea_saw_crm_outboun_8839a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundorder",
            index=models.Index(fields=["status"], name="sea_saw_crm_status_c7d096_idx"),
        ),
        migrations.AddIndex(
            model_name="outbounditem",
            index=models.Index(
                fields=["outbound_qty"], name="sea_saw_crm_outboun_b02ad2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(
                fields=["production_code"], name="sea_saw_crm_product_c8a478_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(fields=["status"], name="sea_saw_crm_status_4b971a_idx"),
        ),
        migrations.AddIndex(
            model_name="productionitem",
            index=models.Index(
                fields=["production_order"], name="sea_saw_crm_product_a8a539_idx"
            ),
        ),
    ]
