# Generated by Django 5.1.2 on 2026-01-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="The company associated with this order.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="sea_saw_crm.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer company for this pipeline",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pipelines",
                to="sea_saw_crm.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="sea_saw_crm.contact",
                verbose_name="Contact",
            ),
        ),
    ]
