# Generated by Django 5.1.2 on 2026-03-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        help_text="Name of the bank.",
                        max_length=255,
                        verbose_name="Bank Name",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Bank account number.",
                        max_length=255,
                        verbose_name="Account Number",
                    ),
                ),
                (
                    "account_holder",
                    models.CharField(
                        blank=True,
                        help_text="Name of the account holder.",
                        max_length=255,
                        null=True,
                        verbose_name="Account Holder",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CNY", "CNY"),
                            ("HKD", "HKD"),
                            ("JPY", "JPY"),
                        ],
                        default="USD",
                        help_text="Currency of the bank account.",
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True,
                        help_text="International bank identifier code (8 or 11 characters).",
                        max_length=11,
                        null=True,
                        verbose_name="SWIFT / BIC Code",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        help_text="Branch name of the bank.",
                        max_length=255,
                        null=True,
                        verbose_name="Branch",
                    ),
                ),
                (
                    "bank_address",
                    models.CharField(
                        blank=True,
                        help_text="Address of the bank or branch.",
                        max_length=255,
                        null=True,
                        verbose_name="Bank Address",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as the primary bank account for this account.",
                        verbose_name="Primary Account",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this bank account.",
                        null=True,
                        verbose_name="Remark",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="The account (company) this bank account belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="sea_saw_crm.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "ordering": ["-is_primary", "bank_name"],
            },
        ),
    ]
