# Generated by Django 5.1 on 2024-11-04 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sea_saw_crm.contact",
            ),
        ),
    ]
