# Generated by Django 5.1.2 on 2025-12-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sea_saw_crm",
            "0002_alter_company_created_by_alter_company_updated_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="sea_saw_crm.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="outbounditem",
            name="outbound_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outbound_items",
                to="sea_saw_crm.outboundorder",
                verbose_name="Outbound Order",
            ),
        ),
        migrations.AlterField(
            model_name="productionitem",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_items",
                to="sea_saw_crm.productionorder",
                verbose_name="Production Order",
            ),
        ),
    ]
