# Generated by Django 5.1 on 2024-11-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0002_alter_deal_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="custom_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="custom_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=10,
                null=True,
                verbose_name="数量",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="closing_date",
            field=models.DateTimeField(verbose_name="完成时间"),
        ),
        migrations.AlterField(
            model_name="deal",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sea_saw_crm.contact",
                verbose_name="联系人信息",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_name",
            field=models.CharField(max_length=255, verbose_name="Deal"),
        ),
        migrations.AlterField(
            model_name="deal",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="详情"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="expected_revenue",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="预期收入",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sea_saw_crm.pipeline",
                verbose_name="Pipeline",
            ),
        ),
    ]
