# Generated by Django 5.1.2 on 2026-01-31 07:21

import sea_saw_crm.models.attachment.attachment
import sea_saw_crm.validators.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0002_add_company_to_order_and_pipeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                help_text="Upload file. Files are organized by entity type and date. Max size: 50MB. Allowed types: PDF, Office documents, images, archives.",
                upload_to=sea_saw_crm.models.attachment.attachment.attachment_file_path,
                validators=[
                    sea_saw_crm.validators.file_validators.validate_file_upload
                ],
                verbose_name="File",
            ),
        ),
    ]
