# Generated by Django 5.1.2 on 2026-04-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0003_bankaccount_rename_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_holder",
            field=models.ForeignKey(
                blank=True,
                help_text="The account (company) this bank account belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="sea_saw_crm.account",
                verbose_name="Account Holder",
            ),
        ),
    ]
