# Generated by Django 5.1 on 2024-11-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0003_contact_custom_fields_deal_custom_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="custom_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sea_saw_crm.contact",
                verbose_name="联系人信息",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sea_saw_crm.pipeline",
                verbose_name="Pipeline",
            ),
        ),
    ]
