# Generated by Django 5.1.2 on 2024-12-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sea_saw_crm', '0005_alter_company_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contact List'},
        ),
        migrations.AlterModelOptions(
            name='customfieldvalue',
            options={'ordering': ['field', 'content_type', 'object_id'], 'verbose_name': 'Custom Field Value', 'verbose_name_plural': 'Custom Field Values'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['deal_name'], 'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['pipeline_name'], 'verbose_name': 'Pipeline', 'verbose_name_plural': 'Pipelines'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['stage_name'], 'verbose_name': 'Stage', 'verbose_name_plural': 'Stages'},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='list_price',
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Associated Company', null=True, on_delete=django.db.models.deletion.CASCADE, to='sea_saw_crm.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='interior_packaging',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Interior Packaging Type'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='progress_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material Stage'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Total Price'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(help_text='The name of the company.', max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text="The company's contact email address.", max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='home_phone',
            field=models.CharField(blank=True, help_text="The company's home phone number, if applicable.", max_length=255, null=True, verbose_name='Home Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile',
            field=models.CharField(blank=True, help_text="The company's mobile phone number.", max_length=255, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, help_text="The company's landline phone number.", max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='custom_fields',
            field=models.JSONField(blank=True, help_text='Additional custom information about the contact, stored as JSON.', null=True, verbose_name='Custom Fields'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text="The contact's email address. Must be unique.", max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, help_text="The contact's first name. Can be empty.", max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, help_text="The contact's last name. Can be empty.", max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, help_text="The contact's landline number. Can be empty.", max_length=255, null=True, verbose_name='Landline'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text="The contact's mobile phone number. Can be empty.", max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, help_text="The contact's job title. Can be empty.", max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_code',
            field=models.CharField(max_length=255, verbose_name='Contract Code'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(verbose_name='Contract Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sea_saw_crm.deal', verbose_name='Associated Deal'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='content_type',
            field=models.ForeignKey(help_text='The type of object to which this custom field value belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='field',
            field=models.ForeignKey(help_text='The custom field associated with this value.', on_delete=django.db.models.deletion.CASCADE, to='sea_saw_crm.field', verbose_name='Custom Field'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='object_id',
            field=models.PositiveIntegerField(help_text='The ID of the object to which this custom field value belongs.', verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='value',
            field=models.TextField(default='', help_text='The value assigned to the custom field.', verbose_name='Field Value'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity involved in the deal.', max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='closing_date',
            field=models.DateTimeField(help_text='Date when the deal is expected to close.', verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Associated contact information for the deal.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sea_saw_crm.contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='custom_fields',
            field=models.JSONField(blank=True, help_text='Customizable fields for additional data.', null=True, verbose_name='Custom Fields'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_name',
            field=models.CharField(help_text='The name of the deal.', max_length=100, verbose_name='Deal Name'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Additional details about the deal.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='expected_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Projected revenue from the deal.', max_digits=10, null=True, verbose_name='Expected Revenue'),
        ),
        migrations.AlterField(
            model_name='field',
            name='content_type',
            field=models.ForeignKey(help_text='The model associated with this field.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(help_text='Name of the field (must be unique within the same content type).', max_length=50, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sea_saw_crm.contract', verbose_name='Associated Contract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_port',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination Port'),
        ),
        migrations.AlterField(
            model_name='order',
            name='etd',
            field=models.DateField(blank=True, null=True, verbose_name='Estimated Delivery Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Order Code'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='Custom Fields'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='glazing',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Glazing Ratio'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sea_saw_crm.order', verbose_name='Associated Order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='packaging',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Packaging Type'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='progress_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Production Progress Quantity'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_name',
            field=models.CharField(help_text='The name of the sales pipeline.', max_length=255, verbose_name='Pipeline Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indicates if the product is available.', verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='The unique product code.', max_length=255, null=True, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(help_text='The name of the product.', max_length=255, unique=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, help_text='The type or category of the product.', max_length=255, null=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='pipeline',
            field=models.ForeignKey(help_text='The pipeline this stage belongs to.', on_delete=django.db.models.deletion.CASCADE, to='sea_saw_crm.pipeline', verbose_name='Pipeline'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_name',
            field=models.CharField(help_text='The name of the stage within the pipeline.', max_length=255, verbose_name='Stage Name'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_sector',
            field=models.IntegerField(default=0, help_text='0: Open Stage; 1: Closed Stage', verbose_name='Stage Sector'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.IntegerField(default=2, help_text='0: Fail; 1: Success; 2: Other', verbose_name='Stage Type'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('email',)},
        ),
    ]
