# Generated by Django 5.1.2 on 2025-01-02 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_saw_crm', '0008_alter_contract_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='deal',
        ),
        migrations.AddField(
            model_name='contract',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sea_saw_crm.contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='balance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Balance Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deposit Date'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='net_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Weight'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='progress_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Production Progress Weight'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_net_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Net Weight'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contract Code'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight'),
        ),
    ]
