# Generated by Django 5.1.2 on 2025-01-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('sea_saw_crm', '0010_alter_contract_options_alter_order_options_and_more')]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Quantity involved in the deal.',
                max_digits=20,
                null=True,
                verbose_name='Amount',
            ),
        ),
        migrations.AlterField(
            model_name='deal',
            name='expected_revenue',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Projected revenue from the deal.',
                max_digits=20,
                null=True,
                verbose_name='Expected Revenue',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total_price',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Total Price'
            ),
        ),
    ]
