# Generated by Django 5.1.2 on 2025-01-15 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_saw_crm', '0011_alter_deal_amount_alter_deal_expected_revenue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='field',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Product', 'verbose_name_plural': 'Order Products'},
        ),
        migrations.AddField(
            model_name='contract',
            name='stage',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('issue_reported', 'Issue Reported')], max_length=25, null=True, verbose_name='Stage'),
        ),
        migrations.AddField(
            model_name='order',
            name='stage',
            field=models.CharField(blank=True, choices=[('in_production', 'In Production'), ('finished_production', 'Finished Production'), ('in_shipment', 'In Shipment'), ('in_payment', 'In Payment'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('issue_reported', 'Issue Reported')], max_length=25, null=True, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sea_saw_crm.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='Custom Fields'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Landline'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sea_saw_crm.contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contract Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sea_saw_crm.contract', verbose_name='Associated Contract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='glazing',
            field=models.FloatField(blank=True, null=True, verbose_name='Glazing Ratio'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='interior_packaging',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Interior Packaging Type'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sea_saw_crm.order', verbose_name='Associated Order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='packaging',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Packaging Type'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='progress_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Production Progress Quantity'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_code'], name='sea_saw_crm_order_c_383188_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stage'], name='sea_saw_crm_stage_8d9f12_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['product_name'], name='sea_saw_crm_product_b5a641_idx'),
        ),
        migrations.DeleteModel(
            name='CustomFieldValue',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='Pipeline',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
