# Generated by Django 5.1.2 on 2025-01-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_saw_crm', '0012_alter_customfieldvalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='stage',
            field=models.CharField(blank=True, choices=[('进行中', 'In Progress'), ('已完成', 'Finished'), ('已取消', 'Cancelled'), ('延迟', 'Delayed'), ('问题单', 'Issue Reported')], max_length=25, null=True, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(blank=True, choices=[('生产中', 'In Production'), ('已完成生产', 'Finished Production'), ('运输中', 'In Shippment'), ('支付中', 'In Payment'), ('完成', 'Finished'), ('已取消', 'Cancelled'), ('延迟', 'Delayed'), ('问题单', 'Issue Reported')], max_length=25, null=True, verbose_name='Stage'),
        ),
    ]
