# Generated by Django 5.1.2 on 2025-02-01 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('sea_saw_crm', '0015_alter_contract_contact_alter_order_contract_and_more')]

    operations = [
        migrations.AlterModelOptions(
            name='order', options={'ordering': ['created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'}
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={
                'ordering': ['created_at'],
                'verbose_name': 'Order Product',
                'verbose_name_plural': 'Order Products',
            },
        ),
    ]
