# Generated by Django 5.1.2 on 2025-03-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0018_alter_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shippment_term",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Shippment Term"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sea_saw_crm.company",
                verbose_name="Company",
            ),
        ),
    ]
