# Generated by Django 5.1.2 on 2025-03-09 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0019_order_shippment_term_alter_contact_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="sea_saw_crm.order",
                verbose_name="Associated Order",
            ),
        ),
    ]
