# Generated by Django 5.1.2 on 2025-03-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_saw_crm", "0020_alter_orderproduct_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=30,
                null=True,
                verbose_name="Total Amount",
            ),
        ),
    ]
