# Generated by Django 5.1.2 on 2026-02-04 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sea_saw_pipeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "payment_code",
                    models.CharField(
                        help_text="Auto-generated unique payment code",
                        max_length=100,
                        unique=True,
                        verbose_name="Payment Code",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("order_payment", "Order Payment"),
                            ("purchase_payment", "Purchase Payment"),
                            ("production_payment", "Production Payment"),
                            ("outbound_payment", "Outbound Payment"),
                        ],
                        default="order_payment",
                        help_text="Type of payment (order, purchase, production, outbound)",
                        max_length=50,
                        verbose_name="Payment Type",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the related entity",
                        null=True,
                        verbose_name="Related Entity ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        help_text="Date when the payment was made",
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Payment amount",
                        max_digits=20,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("CNY", "CNY"),
                            ("HKD", "HKD"),
                            ("JPY", "JPY"),
                        ],
                        default="USD",
                        help_text="Currency code (e.g., USD, CNY)",
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("TT", "Telegraphic Transfer"),
                            ("LC", "Letter of Credit"),
                            ("PayPal", "PayPal"),
                            ("Cash", "Cash"),
                            ("Bank Transfer", "Bank Transfer"),
                        ],
                        help_text="Method used for payment",
                        max_length=50,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank transaction reference number",
                        max_length=255,
                        null=True,
                        verbose_name="Bank Reference",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the payment",
                        null=True,
                        verbose_name="Remark",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of entity: Order, PurchaseOrder, ProductionOrder, or OutboundOrder",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Related Entity Type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        help_text="The business pipeline this payment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sea_saw_pipeline.pipeline",
                        verbose_name="Pipeline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment_type"], name="sea_saw_fin_payment_6acc00_idx"
                    ),
                    models.Index(
                        fields=["pipeline"], name="sea_saw_fin_pipelin_095872_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="sea_saw_fin_content_db2db1_idx",
                    ),
                    models.Index(
                        fields=["payment_code"], name="sea_saw_fin_payment_b88cc8_idx"
                    ),
                ],
            },
        ),
    ]
