
# Generated by Django 5.1.2 on 2026-02-04 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Unique name of the field within the same content type.",
                        max_length=50,
                        verbose_name="Field Name",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("picklist", "Picklist"),
                            ("text", "Text"),
                            ("numerical", "Numerical"),
                            ("lookup", "Lookup"),
                            ("date", "Date"),
                            ("currency", "Currency"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("url", "URL"),
                        ],
                        default="text",
                        help_text="Type of this field, e.g., text, picklist, date.",
                        max_length=50,
                        verbose_name="Field Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the field is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this field is required.",
                        verbose_name="Is Mandatory",
                    ),
                ),
                (
                    "extra_info",
                    models.JSONField(
                        blank=True,
                        help_text="Optional metadata, e.g., picklist choices.",
                        null=True,
                        verbose_name="Extra Information",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The model that this field belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "field_name"),
                        name="unique_field_per_content_type",
                    )
                ],
            },
        ),
    ]
