# Generated by Django 5.1.2 on 2025-12-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=1024)),
                ("status", models.CharField(default="processing", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("download_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
