
# Generated by Django 5.1.2 on 2026-02-04 05:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sea_saw_pipeline", "0001_initial"),
        ("sea_saw_sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "production_code",
                    models.CharField(
                        help_text="Unique code for the production order.",
                        max_length=100,
                        unique=True,
                        verbose_name="Production Code",
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Planned Date"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("issue_reported", "Issue Reported"),
                        ],
                        default="draft",
                        help_text="Production status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes for this production order.",
                        null=True,
                        verbose_name="Remark",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes for this production order.",
                        null=True,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        help_text="The business process pipeline this production order belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_orders",
                        to="sea_saw_pipeline.pipeline",
                        verbose_name="Pipeline",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales order (legacy field, use pipeline.order instead).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders_legacy",
                        to="sea_saw_sales.order",
                        verbose_name="Related Order (Legacy)",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Order",
                "verbose_name_plural": "Production Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Product Name"),
                ),
                (
                    "specification",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Specification",
                    ),
                ),
                (
                    "outter_packaging",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Outter Packaging",
                    ),
                ),
                (
                    "inner_packaging",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Inner Packaging",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Size"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("kgs", "KGS"), ("lbs", "LBS")],
                        default="kgs",
                        max_length=20,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "glazing",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Glazing (%)",
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Gross Weight",
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Net Weight",
                    ),
                ),
                (
                    "planned_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Planned Quantity",
                    ),
                ),
                (
                    "produced_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total actual produced quantity.",
                        max_digits=10,
                        verbose_name="Produced Quantity",
                    ),
                ),
                (
                    "produced_net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Outbound Net Weight",
                    ),
                ),
                (
                    "produced_gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Outbound Gross Weight",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The sales order item linked to this production item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_items",
                        to="sea_saw_sales.orderitem",
                        verbose_name="Related Order Item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_items",
                        to="sea_saw_production.productionorder",
                        verbose_name="Production Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Item",
                "verbose_name_plural": "Production Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(
                fields=["production_code"], name="sea_saw_pro_product_36c9c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(fields=["status"], name="sea_saw_pro_status_7126ff_idx"),
        ),
        migrations.AddIndex(
            model_name="productionitem",
            index=models.Index(
                fields=["production_order"], name="sea_saw_pro_product_64f97f_idx"
            ),
        ),
    ]
