# Generated by Django 5.1.2 on 2026-02-04 05:24

import django.db.models.deletion
import sea_saw_attachment.utils.file_path
import sea_saw_attachment.validators.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("order_attachment", "Order Attachment"),
                            ("production_attachment", "Production Attachment"),
                            ("purchase_attachment", "Purchase Attachment"),
                            ("outbound_attachment", "Outbound Attachment"),
                            ("payment_attachment", "Payment Attachment"),
                        ],
                        help_text="Type of attachment (order, production, purchase, outbound, payment)",
                        max_length=50,
                        verbose_name="Attachment Type",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="ID of the related entity",
                        verbose_name="Related Entity ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload file. Files are organized by entity type and date. Max size: 50MB. Allowed types: PDF, Office documents, images, archives.",
                        upload_to=sea_saw_attachment.utils.file_path.attachment_file_path,
                        validators=[
                            sea_saw_attachment.validators.file_validators.validate_file_upload
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True,
                        help_text="Original filename for display purposes.",
                        max_length=255,
                        verbose_name="File Name",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="File Size (bytes)"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of the file.",
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of entity: Order, ProductionOrder, PurchaseOrder, OutboundOrder, or Payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Related Entity Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["-created_at"],
            },
        ),
    ]
